name: sansadtv_app
description: "Sansad TV Mobile application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  youtube_player_iframe: ^4.0.4
  http: ^1.1.2
  url_launcher: ^6.2.3
  universal_html: ^2.2.4
  intl: ^0.19.0
  flutter_native_splash: ^2.3.9
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
flutter_native_splash:
  color: "#942B72"
  image: images/logo-sansad.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#942B72"
    image: images/splash_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  adaptive_icon_background: "#942B72"
  adaptive_icon_foreground: "images/logo-sansad.png"
  image_path: "images/logo-sansad.png"
  image_path_ios: "images/logo-sansad.png"